<?php

namespace Drupal\profile\Form;

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Form\FormStateInterface;

class ProfileForm extends ContentEntityForm
{
  public function buildForm(array $form, FormStateInterface $form_state) {
    $form = parent::buildForm($form, $form_state);
//    $form['birth_day'] = [
//      '#title' => t('Date de naissance'),
//    ];
    return $form;
  }

  public function save(array $form, FormStateInterface $form_state) {
    $entity = $this->getEntity();
    $entity->save();
    $form_state->setRedirect('entity.profile.collection');
//    return parent::save($form, $form_state); // TODO: Change the autogenerated stub
  }

}
