<?php

/**
 * @file
 * Primary module hooks for Exemple module.
 */

use Drupal\Core\Render\Element;
use Drupal\exemple\Entity\Exemple;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function exemple_theme() {
  return [
    'exemple' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for exemple templates.
 *
 * Default template: exemple.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the exemple information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_exemple(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function exemple_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish exemples.
      $storage = \Drupal::entityTypeManager()->getStorage('exemple');
      $exemple_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($exemple_ids) as $exemple) {
        $exemple->set('status', FALSE);
        $exemple->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize exemples.
      $storage = \Drupal::entityTypeManager()->getStorage('exemple');
      $exemple_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($exemple_ids) as $exemple) {
        $exemple->setOwnerId(0);
        $exemple->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function exemple_user_predelete(UserInterface $account) {
  // Delete exemples.
  $storage = \Drupal::entityTypeManager()->getStorage('exemple');
  $exemple_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $exemples = $storage->loadMultiple($exemple_ids);
  $storage->delete($exemples);
  // Delete old revisions.
  $exemple_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->execute();
  foreach (array_keys($exemple_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
